model_id: meta-llama/Llama-3.2-1B
tokenizer_id: meta-llama/Llama-3.2-1B
train_file: data/sample.conll
eval_file: data/test.conll
final_model_dir: artifacts/final-model
labels:
  - B-T
  - I-T
  - O
label_all_tokens: false
